---
title: "10 Reading Big Data(bases)"
author: "Peter Baumgartner"
date: "`r Sys.Date()`"
output: 
  html_notebook: 
   # next three lines define start of chapter numbers
    pandoc_args: [ 
      "--number-offset=10,0" 
    ]
    fig_caption: true
    number_sections: yes
    toc: yes
    toc_depth: 3
---
```{r label = "global-options", echo=FALSE, highlight=TRUE}
knitr::opts_chunk$set(
        message = F,
        error = F,
        warning = F,
        comment = NA,
        highlight = T,
        prompt = T
        )

### install and load some important packages
### https://github.com/tidyverse/tidyverse
if (!require("tidyverse"))
        {install.packages("tidyverse", repos = 'http://cran.wu.ac.at/')
        library(tidyverse)}

### above command installed and loaded the core tidyverse packages:
# ggplot2, for data visualisation.
# dplyr, for data manipulation.
# tidyr, for data tidying.
# readr, for data import.
# purrr, for functional programming.
# tibble, for tibbles, a modern re-imagining of data frames

### above command installed but did not load yet the following packages:

### Working with specific types of vectors:
# hms, for times.
# stringr, for strings.
# lubridate, for date/times.
# forcats, for factors.

### Importing other types of data:
# feather, for sharing with Python and other languages.
# haven, for SPSS, SAS and Stata files.
# httr, for web apis.
# jsonlite for JSON.
# readxl, for .xls and .xlsx files.
# rvest, for web scraping.
# xml2, for XML.

### Modelling
# modelr, for modelling within a pipeline
# broom, for turning models into tidy data
```

## Loading required packages

```{r laoding-required-packages}
# library(checkpoint)
# following line produces error, I would need to install this old r version
# checkpoint("2016-09-04", R.version = "3.3.1") 
library(devEMF)
# library(RPostgreSQL) # gives error, see Evernote
library(DBI)
library(RSQLite)
library(jsonlite)
library(tm)
library(wordcloud)
# library(RMongo) # gives error ("package ‘rJava’ could not be loaded"), see Evernote
library(data.table)
options(width = 80) # only 70 characters per line
```

## SQLite and R

```{r check-connection}
con1 = dbConnect(SQLite(), dbname = "~/Documents/Meine DBs/sqlite/LiteDB.db")
dbIsValid(con1)
```

```{r load-db-with-iris-data}
diris <- as.data.table(iris)
dbWriteTable(con1, "Iris", tiris, overwrite = TRUE,
             append = FALSE)
dbListTables(con1)
dbListFields(con1, "Iris")
```

```{r read-sqlite-table}
diris_lite1 <- dbReadTable(con1, "Iris")
diris_lite1 <- as.data.table(diris_lite1)
all.equal(diris, diris_lite1)
```
```{r my-first-db-query}
query <-
        dbSendQuery(con1, "SELECT [Sepal.Length] FROM Iris WHERE Species = 'setosa'")
diris_lite2 <- dbFetch(query, n = -1)
head(diris_lite2)
dbClearResult(query)
```
```{r my-second-query}
query <-
        dbSendQuery(con1,
                    "SELECT [Sepal.Length], Species FROM Iris Where Species <> 'setosa'")
diris_lite3 <- dbFetch(query, n = -1)
head(diris_lite3)
dbClearResult(query)
```
```{r my-third-query}
query <-
        dbSendQuery(con1, "SELECT * FROM Iris Where Species <> 'setosa'")
diris_lite4 <- dbFetch(query, n = -1)
diris_lite4 <- as.data.table(diris_lite4)
diris_lite4
dbClearResult(query)
```

## Big Data 

These next two examples demonstrate how large data may be pushed be mindful of your available RAM if you decide to experiment just choose one of these is our advice.

```{r big-data-test-small}
# 534.1Mb of 70,000,000 elements
BigData <- rnorm(70000000)
BigData <- as.data.table(BigData)
# writes about 0.5Gb to our SQLite database file
# The names match both in R and SQLite
dbWriteTable(con1, "BigData", BigData)
dbListTables(con1)
```

```{r real-big-data-test}
# the default connection to SQLite has a 2Gb 'cap'
# 1.5Gb of 200,000,000
BiggerData <- rnorm(200000000, 1)
BiggerData <- as.data.table(BiggerData)
# writes about 1.5Gb to our SQLite database file
# The names match both in R and SQLite
dbWriteTable(con1, "BiggerData", BiggerData)
dbListTables(con1)
```
## Delete tables

```{r drop-tables}
dbRemoveTable(con1, "BigData")
dbRemoveTable(con1, "BiggerData")
dbListTables(con1)
```

## Close connection

```{r disconnect}
dbDisconnect(con1)
dbIsValid(con1)
rm(diris_lite1, diris_lite2, diris_lite3, diris_lite4)
```
## MongoDEB and R


